programs/validator-history/src/state.rs

Allows easy access of fields without needing to do range math or default checks when computing on validator history state

Utilities for accessing validator history state

---

keepers/validator-keeper/src/lib.rs
keepers/validator-keeper/src/main.rs
keepers/validator-keeper/src/mev_commission.rs
programs/validator-history/idl/validator_history.json
programs/validator-history/src/instructions/copy_tip_distribution_account.rs
programs/validator-history/src/instructions/mod.rs
programs/validator-history/src/instructions/update_mev_commission.rs
programs/validator-history/src/lib.rs
programs/validator-history/src/state.rs
programs/validator-history/src/utils.rs
tests/src/fixtures.rs
tests/tests/test_mev_commission.rs

I took a stab at #6 , saw it's been open for a few weeks
mainly out of wanting to learn, this is my first experience w/ Anchor, solana programs, instructions etc etc
I'd love a review to see if I thought about the issue correctly, but i'm happy to close it out or collaborate w/ the assignee of #6 to get this in

feat: add MEV earned per epoch in the ValidatorHistoryAccount

---

keepers/keeper-core/src/lib.rs
keepers/validator-keeper/src/cluster_info.rs
keepers/validator-keeper/src/gossip.rs
keepers/validator-keeper/src/lib.rs
keepers/validator-keeper/src/main.rs
keepers/validator-keeper/src/mev_commission.rs
keepers/validator-keeper/src/stake.rs
keepers/validator-keeper/src/vote_account.rs

Improves keeper reliability for landing transactions by:
* no longer skipping transactions that initially fail with a BlockhashNotFound error
* Merging vote accounts with all validator history accounts for epoch credit cranking, so offline validators that no longer showing up in getVoteAccounts still get cranked (necessary for Steward program scoring)
The first part has already been running on mainnet for a week, and for the last 3 epochs, all vote accounts have been updated each epoch (as measured by: same number of commissions tracked as stakes).

Improve Keeper Reliability

---

programs/validator-history/Cargo.toml
programs/validator-history/src/allocator.rs
programs/validator-history/src/lib.rs
tests/src/fixtures.rs
tests/tests/test_cluster_history.rs

The SlotHistory sysvar is too big to deserialize on the stack, and too big for the default heap size (32kb). Solana supports up to 256KB of heap, but a custom heap implementation is needed, even if you request an increased heap size with the compute budget instruction, since the default global_allocator just uses the hard-coded 32kb.
Mango's custom heap implementation implements a bottom-up heap as opposed to the top-down heap implemented by `solana_program::entrypoint:BumpAllocator`. The issue with the top down approach is, if you initialize the standard BumpAllocator with a larger heap length, instructions that don't need the extra heap space will start out allocating outside of the default heap bounds unless they submit a request_heap_frame instruction. By allocating from bottom up, …

Implement custom heap to support SlotHistory deserialization

---

keepers/validator-keeper/src/cluster_info.rs
programs/validator-history/src/instructions/copy_cluster_info.rs
tests/src/fixtures.rs
tests/tests/test_cluster_history.rs

Some of the logic around reading partial blocks was slightly off, especially for cases where there are no full blocks in between the start and end slot. Also, making sure we don't read slots past the current slot when updating current epoch.

Math fixes for cluster history slot counting

---

.github/workflows/build.yaml

Due to the below error, this package needs to be upgraded, and the old version is pinned in solana dependencies, however none of the solana 1.16 versions will get the upgrade.  This repo will need its dependencies upgraded to v1.17 on the agave once the below PR is merged. Additionally, there may be issues with solana-program-test in 1.17 that will need to be worked out.
https://github.com/anza-xyz/agave/pull/930
```
Run cargo audit --ignore RUSTSEC-2022-0093 --ignore RUSTSEC-2023-0065
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
Loaded 621 security advisories (from /home/runner/.cargo/advisory-db)
Updating crates.io index
Scanning Cargo.lock for vulnerabilities (63[4](https://github.com/jito-foundation/stakenet/actions/runs/8759384154/job/24042265021?pr=31# …
```

Disable rustls warning until upgrade to v1.17 agave

---

keepers/validator-keeper/src/lib.rs

Added two new metrics to the `emit_validator_history_metrics` function:
- `num_live_validator_histories`: The number of validator history accounts that have "live" vote accounts with the owner of said vote account being the vote program
- `num_get_vote_accounts_voting`: The number of vote accounts actually voting. More specifically, accounts that have voted in the current epoch retrieved from `get_vote_accounts_with_retry`.

FEATURE: Adding metrics - num_get_vote_accounts_voting, num_live_validator_histories

---

Cargo.toml
programs/validator-history/idl/validator_history.json
programs/validator-history/src/errors.rs
programs/validator-history/src/instructions/copy_vote_account.rs
programs/validator-history/src/state.rs
programs/validator-history/src/utils.rs
tests/tests/test_vote_account.rs

Problem: 
Due to unreliability in landing transactions in epoch 598 (when chain was super congested), about half of active validators did not get a single ValidatorHistoryEntry created, so their epoch credits were never copied over in future epochs. This is bad for Stakenet scoring, and this issue could happen in the future if congestion gets bad again.
Solution:
In the CopyVoteAccount instruction, when epochs are detected in the vote account that don't exist in the CircBuf, insert those new entries and shift all entries with greater epochs forward by one. This will evict the oldest entries if we are wrapping around. After that, epoch credits are copied to the old entries. We will then be able to retroactively call:
`CopyTipDistributionAccount` and `UpdateStakeHistory` on those …

Insert missing entries in CopyVoteAccount

---

programs/steward/idl/steward.json
programs/steward/src/delegation.rs
programs/steward/src/events.rs
programs/steward/src/instructions/auto_add_validator_to_pool.rs
programs/steward/src/instructions/auto_remove_validator_from_pool.rs
programs/steward/src/instructions/epoch_maintenance.rs
programs/steward/src/instructions/rebalance.rs
programs/steward/src/lib.rs
programs/steward/src/state/steward_state.rs
tests/tests/steward/test_algorithms.rs

Puts all events except for Scoring / instant unstake response types in a single file

More events emitted

---

programs/steward/idl/steward.json
programs/steward/src/instructions/epoch_maintenance.rs
programs/steward/src/instructions/realloc_state.rs
programs/steward/src/instructions/reset_steward_state.rs
programs/steward/src/state/steward_state.rs
tests/src/steward_fixtures.rs
tests/tests/steward/test_state_transitions.rs
utils/steward-cli/src/commands/info/view_state.rs

- Added status flags for better tracking of the state machine
- Fixed issue on new epoch not being able to reset state to idle

REFACTOR: Added status flags

---

programs/steward/idl/steward.json
programs/steward/src/instructions/compute_delegations.rs
programs/steward/src/instructions/compute_instant_unstake.rs
programs/steward/src/instructions/compute_score.rs
programs/steward/src/instructions/epoch_maintenance.rs
programs/steward/src/instructions/idle.rs
programs/steward/src/instructions/rebalance.rs
programs/steward/src/state/steward_state.rs
programs/steward/src/utils.rs
tests/src/steward_fixtures.rs
tests/tests/steward/test_integration.rs
utils/steward-cli/src/commands/cranks/compute_delegations.rs
utils/steward-cli/src/commands/cranks/idle.rs

The new `crank_checks` function does all of the checks needed across each crank. Now with the new addition of looking for mismatched indices.

FEATURE: Adding re-usable crank_checks function

---

programs/steward/idl/steward.json
programs/steward/src/errors.rs
programs/steward/src/instructions/instant_remove_validator.rs
programs/steward/src/utils.rs

The issue is that if 2 validators are put into `DeactivatingValidator` one marked for instant removal and the other for regular removal. The function `instant_remove_validator` will not be able to run, halting the state machine for the epoch. This is because `instant_remove_validator` is checking to see that all validators are not in `DeactivatingValidator` or `ReadyForRemoval`. However since the discovery that regular removals can also go directly to `DeactivatingValidator` this check is no longer valid.
The fix is to tally all of the deactivating StakeStatus across the validator list and assert that the count is equal to the regular removed validators, then we can safely assume all of the immediate to remove validators are already removed from the list.

FIX: Fixed instant removal validator stuck scenario

---

programs/steward/src/instructions/compute_instant_unstake.rs
programs/steward/src/instructions/rebalance.rs

Currently a single lingering ComputeInstantUnstake or Rebalance step can be executed if the Steward was left in this state after rolling over to a new epoch. This can affect stake based on outdated information which we don't want. Force the transition to Idle so everything is handled normally.

Force state transitions to Idle before doing work in new epoch

---

programs/steward/src/score.rs
programs/validator-history/src/state.rs
tests/tests/steward/mod.rs
tests/tests/steward/test_scoring.rs

Added comprehensive tests for the scoring component calculations, to make sure that no functionality has changed with the refactor.

Unit tests for scoring components

---

keepers/stakenet-keeper/src/entries/crank_steward.rs
programs/steward/src/instructions/epoch_maintenance.rs
programs/steward/src/instructions/instant_remove_validator.rs
programs/steward/src/state/steward_state.rs

Problem: A bug was found where validators who are added to the pool outside of the boundary of the Steward state, then removed before they begin getting tracked (validators added during cycle N are tracked in steward state in cycle N+1) were not getting properly removed. This caused the state machine to get stuck because the invariant used to keep the state aligned was failing (`num_pool_validators + validators_added - validators_to_remove == validator_list.len()`)
Resolution: Make sure we're shifting values for steward state fields that can be relevant past `num_pool_validators` (which is just the validators_to_remove and validators_for_immediate_removal). We also don't want to clear those values at `num_pool_validators` because that might be a relevant value.

Fix for removed validator past boundary

---

.github/workflows/build.yaml
programs/steward/Cargo.toml
programs/steward/src/events.rs
programs/steward/src/instructions/rebalance.rs
programs/steward/src/instructions/set_new_authority.rs
programs/steward/src/lib.rs
programs/steward/src/score.rs
programs/steward/src/state/parameters.rs
programs/steward/src/state/steward_state.rs
programs/steward/src/utils.rs
programs/validator-history/Cargo.toml

Recommendation from #48. Should help compilation issues downstream.

No idl-build in default target

---

utils/validator-history-cli/src/main.rs

Currently, has an error when we want to initialize config by  `validator-history-cli` .
```
Command init-config: Short option names must be unique for each argument, but '-t' is in use by both 'tip_distribution_program_id' and 'tip_distribution_authority
```
- Remove short option.

Fix: `init-config` command of `validator-history-cli` 

---

Cargo.lock
Cargo.toml
api/Cargo.toml
api/README.md
api/src/bin/main.rs
api/src/error.rs
api/src/lib.rs
api/src/router.rs
api/src/router/get_all_validator_histories.rs
api/src/router/get_latest_validator_history.rs

Feature: Build a StakeNet API

---

.github/workflows/build.yaml
keepers/stakenet-keeper/src/entries/crank_steward.rs

There was a keeper crash because it unwrapped an empty epoch credits list.

PATCH: Empty Epoch Credits

---

.github/workflows/build.yaml
docker-compose.yaml
keeper-bot-quick-start.md
keepers/stakenet-keeper/src/main.rs
keepers/stakenet-keeper/src/state/keeper_config.rs

**Problem**
We would like to scale up our keeper instances for redundancy purposes but lack the necessary changes to differentiate between replicas of a service from a metrics perspective.
**Solution**
- Use the `HOSTNAME` env var as a component of the `solana_metrics` `host_id` to differentiate between replicas in our monitoring systems
- Use `REGION` env var as a component of the `solana_metrics` `host_id` for triage purposes
- Ignore RUSTSEC-2025-0022 - this has been ignored upstream
**Local Run Log Output**
See `solana_metrics::metrics host id`
```
[2025-04-07T23:10:57Z INFO  stakenet_keeper] Stakenet Keeper Configuration:
-------------------------------
JSON RPC URL: INCLUDE YOUR RPC URL HERE
Gossip Entrypoint: None
Keypair Path: "./credentials/keypair.json"
Oracle Authority Keypair …
```

Keeper: use hostname + region in metrics host id

---

.github/workflows/build.yaml
docker-compose.yaml
keepers/stakenet-keeper/src/main.rs
keepers/stakenet-keeper/src/operations/keeper_operations.rs
keepers/stakenet-keeper/src/operations/metrics_emit.rs
keepers/stakenet-keeper/src/state/keeper_config.rs
keepers/stakenet-keeper/src/state/keeper_state.rs

**Problem**
We would like to differentiate between keeper hosts running against different Solana network clusters but lack the ability to do so with our existing metrics setup.
**Solution**
- Wire thru `cluster_name` to `datapoint_info!` calls to be provided as a tag
- Add `REGION` env var to metrics only container

keeper: Add a cluster tag to emitted metrics

---

programs/steward/src/score.rs
programs/validator-history/src/instructions/copy_priority_fee_distribution.rs
programs/validator-history/src/instructions/copy_tip_distribution_account.rs
programs/validator-history/src/instructions/update_priority_fee_history.rs
programs/validator-history/src/state.rs
tests/tests/steward/test_algorithms.rs
tests/tests/steward/test_scoring.rs

```
test steward::test_cycle::test_cycle ... ok
test result: ok. 126 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.34s
Doc-tests tests
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

feat: validator history priority fee support

---

programs/steward/src/score.rs
tests/tests/steward/test_scoring.rs

**Problem**
The priority fee merkle root upload authority is not yet a component of the score despite appearing to be in the unstake and scoring details.
**Solution**
- Include priority fee merkle root upload authority as a component of scoring
- Ensure that an Unset authority results in a score of 1.0 to default to not penalizing the validator in this scenario

feat: use priority fee merkle root upload authority as scoring component

---

keepers/stakenet-keeper/src/entries/crank_steward.rs

`Issue` -- Steward scoring was stalling. Each `ComputeScore` instruction consumes roughly 140,000 CUs. And we were packing 10 of them per transaction. That puts us very close to the 1.4m limit we were requesting.
`Fix` --  Pack 5 of these instructions per transaction. And bump requested CU per ix to 200,000 for a cushion.
Also added a new grafana alert that will notify when the number of scored accounts hasn't progressed in the last hour (and is below the expected to be scored). Have this alert set to low sev for now. Will keep an eye on it and tune accordingly.

Increase CUs for Steward Scoring
